### ISSUE TITLE
NA vs supressed values

### ISSUE THREAD

**Issue by chfoster** [dfe-analytical-services/leo-graduate-industry-dashboard#32]
In all underlying data files, supressed values are recorded as NA. In the reactable options we can set NA = 'x' or 'c' but this calls both supressed and derived NAs the same thing which is wrong. 

We want any underlying data NA's to be labelled as c, and any derived NA's (due to missing rows) to be labelled as x. My suggestion would be re-labelling supressed values in the underlying data as c, so that the only NA's are derived, however, this causes issues as it means rows are no longer numeric when they contain character vaues.

**Comment by rmbielby** [comment]
Spotted this behaviour whilst scanning through on some testing. 0 is suppressed in the body of the table, the total isn't
a) zeros don't need suppressing.
b) the rules should be the same between the table body and the summary total row.

![image](https://user-images.githubusercontent.com/230859/163156766-8613bb63-e509-4ba4-aab8-2e7c47f63c40.png)
