### ISSUE TITLE
Force the tables to fit within the window

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/leo-graduate-industry-dashboard#38]
Thinking of instances like this where we should try to shrink the first column a bit and stop the table overspilling to the right:

![image](https://user-images.githubusercontent.com/52536248/161627734-0bcc58e7-4881-404b-aab3-7aa509bdfb65.png)

**Comment by chfoster** [comment]
@cjrace would you consider this closed?

**Comment by cjrace** [comment]
Yeah, we reduced the width of the sidebar and now the balance and spacing feels a lot better for now
