### ISSUE TITLE
Tidy up whitespace on industry by subject table

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/leo-graduate-industry-dashboard#40]
Go to industry by subject tab

Select industry as the breakdown

![image](https://user-images.githubusercontent.com/52536248/161801185-a7e4e5dd-a848-43f4-b8a4-24cf326a73e5.png)

I wasn’t sure if there was a way to have the industry names shorter with a ‘…’ and then you have to hover or click to see the full name?

**Comment by chfoster** [comment]
@cjrace @rmbielby Can we close this? :)

**Comment by rmbielby** [comment]
Yep, provided Kirti et al are happy with how we've dealt with it?
